export const issueActionTypes = {
  ISSUES_REQUEST: "ISSUES_REQUEST",
  ISSUES_SUCCESS: "ISSUES_SUCCESS",
  ISSUES_FAILURE: "ISSUES_FAILURE",
  ISSUE_REQUEST: "ISSUES_FAILURE",
  ISSUE_SUCCESS: "ISSUE_SUCCESS",
  ISSUE_FAILURE: "ISSUE_FAILURE",
};
